version: '3.3'
services:
  about:
    container_name: about_c
    build: ./about/
    image: aakashgaur57/about
    ports:
      - 1122:80
  contact:
    container_name: contact_c
    build: ./contact/
    image: aakashgaur57/contact
    ports:
      - 1123:80
  courses:
    container_name: courses_c
    build: ./courses/
    image: aakashgaur57/courses
    ports:
      - 1124:80
  exams:
    container_name: exam_c
    build: ./examss/
    image: aakashgaur57/examss
    ports:
      - 1125:80
  home:
    container_name: home_c
    build: .//
    image: aakashgaur57/
    ports:
      - 1126:80  
  mongo:
    container_name: mongo_c
    build: ./mongodb/
    image: aakashgaur57/mongo
    ports:
      - 1127:27017 
  nodeapp:
    container_name: nodeapp_c
    build: ./nodeapp/
    image: aakashgaur57/nodeapp
    ports:
      - 1128:3000  
        # environment:
            #    MONGO_URI: mongodb://192.168.29.29:1127/mydb
  login:
    container_name: login_c
    build: ./login_register/
    image: aakashgaur57/login_register
    ports:
      - 1129:80 
